### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by taich001** [a-sit-plus/at-registrierkassen-mustercode#217]
Es ist mir leider nicht gelungen den Demo-Code unter Windows zum Laufen zu bringen.
Gibt es eine Beschreibung wie man den Demo-Code zum Laufen bringt.

Im Vorraus vielen Dank für die Hilfe.

**Comment by lebail** [comment]
Das steht alles direkt auf der Startseite <https://github.com/a-sit-plus/at-registrierkassen-mustercode> unter dem Punkt "Verwendung des Democodes und der Demokasse". Mit den dortigen Informationen konnte ich den Code völlig problemlos sowohl unter Debian Linux als auch unter Windows ausführen.

Vielleicht können Sie ja genauer beschreiben, was bei Ihnen nicht klappt.

**Comment by taich001** [comment]
Wenn ich das Projekt mit Github "clone 
https://github.com/a-sit-plus/at-registrierkassen-mustercode.git" 
downloade, finde ich 78 Dateien in 188 Verzeichnissen auf meinem 
Computer und kann nicht erkennen wo ich beginnen soll und was ich mit 
den vielen Dateien anfangen soll.

-- 
Viele Grüße
Thomas Aichinger

----------------------------
http://www.datamagic.at
----------------------------
Data Magic Datenservice GmbH
Schönbrunner Straße 140
1120 Wien

Am 06.01.2017 um 09:08 schrieb lebail:

**Comment by twisted-pear** [comment]
das git repo enthält den quellcode für die demo kassa, es gibt ein zip mit den fertigen jar files unter "releases": https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/V1.0.0/regkassen-demo-1.0.0.zip

**Comment by taich001** [comment]
Gibt es so etwas wie eine Entwicklungsumgebung mit der ich den Code ansehen kann?
Was findet man in den 3 Verzeichnissen regkassen-common, regkassen-core und regkassen-democashbox? Handelt es sich um ein oder mehrere eigenständige Programme? Gibt es so etwas wie eine Funktion Main() mit der das Programm startet und wo findet man die?

Vielen Dank für die Hilfe.

**Comment by ckvsoft** [comment]
Ist jetzt aber kein Spaß? 
VI,  UltraEdit, NetBeans ...

**Comment by ErichFreitag** [comment]
@taich001 - wenn ich aus meiner Sicht dazu etwas beitragen kann:

Die Spezifikation, was eine RKSV-Kasse tut ist das Dokument "Detailfragen" der A-SIT. Das definiert technische Details der RKSV und der verbundenen Dokumente wie dem Erlass etc.

Der Mustercode zeigt, wie das in Java beispielhaft umgesetzt wird. Wenn sie z.B. schauen möchten, wie das mit der Verschlüsselung des Umsatzzählers funktioniert, dann habe sie im Detailfragen-Dokument im Punkt 2.5.3 (Verschlüsselung) einen Link auf das Modul CryptoUtil.Java und auf die zugehörigen Methoden wie encryptXXX. 

Der Mustercode stellt zusätzlich eine Demokasse dar, mit der Testfälle abgearbeitet und Belegdaten erzeugt werden können.

**Comment by taich001** [comment]
Ach so, ich dachte Sie kennen irgendein Tool mit dem man die 78 Dateien in den 188 Verzeichnisen vernünftig ansehen und analysieren kann. Auch hätte ich nach einer make-Datei oder einer Anweisung wie man den Mustercode übersetzt gesucht.

Aktuell würde mich noch interessieren ob es eine Beschreibung der Datei cryptographicMaterialContainer.json gibt damit ich das Prüftool mit meinen eigenen Werten verwenden kann.

**Comment by ckvsoft** [comment]
NetBeans zb.

**Comment by lebail** [comment]
Die Datei cryptographicMaterialContainer.json ist im Detailfragen-Dokument <https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf> spezifiziert. Dort stehen übrigens auch viele weitere brauchbare Dinge.

Noch ein Tipp: Es ist nicht zwangsläufig notwendig, den gesamten Democode durchzuarbeiten - schon gar nicht, wenn man vielleicht eine andere Programmiersprache als Java benutzt. An sich reicht es, die RKSV, den zugehörigen Erlass und das Detailfragen-Dokument zu lesen.

Ich z.B. habe den Democode praktisch nicht verwendet (außer in der Anfangsphase, als es noch kein Detailfragen-Dokument gab, und der Democode zur Klarstellung einiger Kleinigkeiten - vor allem dem Format des Umsatzzählers - diente) und habe dennoch eine funktionierende Implementierung zustande gebracht.

Das Prüftool verwende ich natürlich sehr wohl, aber dazu ist kein Studium des Democodes erforderlich.

**Comment by cmaxmedia** [comment]
Auf A-Trust kann man einen Windows Code in c# herunterladen. Hat mir sehr geholfen:
http://labs.a-trust.at/developer/source.aspx

**Comment by ad1240de** [comment]
Kann mir jemand erklären was ZDA bedeutet und welche ZDA's gibts ?
Danke
Andreas

**Comment by ErichFreitag** [comment]
ZDA war die alte Bezeichnung "ZertifikatsDiensteAnbieter", wurde mit der eIDAS-Verordnung auf VDA (VertrauensDiensteAnbieter) geändert.

Geben tut es theoretisch einige, üblich und in Österreich beheimatet sind A-Trust, Global Trust und Prime Sign.

P.S. für neue Themen bitte neue Issues anlegen.

**Comment by ad1240de** [comment]
Danke,

und wenn die Karte bei A-Trust inkl. Zertifikat gekauft wordn ist, was soll dann beim Registrierkassenalgorithmuskennzeichen _R1-XXXX_ stehen ?

 

lg

Andreas 

 

Von: Erich Freitag [mailto:notifications@github.com] 
Gesendet: Donnerstag, 26. Jänner 2017 15:30
An: a-sit-plus/at-registrierkassen-mustercode
Cc: ad1240de; Comment
Betreff: Re: [a-sit-plus/at-registrierkassen-mustercode] Demo Code (#217)

 

ZDA war die alte Bezeichnung "ZertifikatsDiensteAnbieter", wurde mit der eIDAS-Verordnung auf VDA (VertrauensDiensteAnbieter) geändert.

Geben tut es theoretisch einige, üblich und in Österreich beheimatet sind A-Trust, Global Trust und Prime Sign.

P.S. für neue Themen bitte neue Issues anlegen.

**Comment by ErichFreitag** [comment]
Für A-Trust _R1-AT1.
Für Global Trust _R1-AT2.
Für Prime Sign _R1-AT3.

**Comment by ad1240de** [comment]
DankeMfgAndreas Dubas 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Erich Freitag <notifications@github.com> Datum: 26.01.17  16:12  (GMT+01:00) An: a-sit-plus/at-registrierkassen-mustercode <at-registrierkassen-mustercode@noreply.github.com> Cc: ad1240de <email@dubasgmbh.com>, Comment <comment@noreply.github.com> Betreff: Re: [a-sit-plus/at-registrierkassen-mustercode] Demo Code (#217) 
Für A-Trust _R1-AT1.

Für Global Trust _R1-AT2.

Für Prime Sign _R1-AT3.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/a-sit-plus/at-registrierkassen-mustercode","title":"a-sit-plus/at-registrierkassen-mustercode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/a-sit-plus/at-registrierkassen-mustercode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ErichFreitag in #217: Für A-Trust _R1-AT1.\r\nFür Global Trust _R1-AT2.\r\nFür Prime Sign _R1-AT3."}],"action":{"name":"View Issue","url":"https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/217#issuecomment-275412686"}}}
