### ISSUE TITLE
Empty fields in new DEP export format in version 0.6 

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#55]
Within the context of changes in new "example-output-0.6.zip" package in comparison with version 0.5, especially in the content of the "dep-export.json" file. I would like to ask several important questions:

1. As both fields in the file ("Signaturzertifikat", "Zertifizierungsstellen") are empty, is it allowed to prepare SW of the cash register which create a dep-export file with such empty fields ("Signaturzertifikat", "Zertifizierungsstellen") and create additional file "cryptographicMaterialContainer.json" during export operation, which does not contain field "Zertifizierungsstellen"?

2.  Do I understand correctly the fact that there is not necessary to handle field "Zertifizierungsstellen" at all?

3. In the example 0.6 there are used 3 different certificates (also placed in the file "cryptographicMaterialContainer.json" ) which are used for signing of the receipts alternately. Is such using of the certificates proper? (Hint at Annex "Detailspezifikationen" point 7: "Anmerkung zum Wechsel des Signaturzertifikats: Bei einem Wechsel des Signaturzertifikats muss garantiert sein, dass weitere Belege nicht mehr mit dem vor dem Wechsel verwendeten Zertifikat signiert werden dürfen.")

**Comment by asitplus-pteufl** [comment]
Since your are writing in English, I will answer your questions and then summarize the important issues of the German V1.1 Document.

1.
cryptographicMaterialContainer.json is ONLY required for the verification tool. This is not a file/format required by the regulation. Only the dep-export file/format is mandatory. If you want to be able to verify your generated receipts/DEP file with the provided verification tools, then you need to provide this file. Those tools will be extended in V0.7 (coverage of test cases etc.)

2. yes you are right, the inclusion of the signing certificate and CA certificates is optional. Especially, when you have a system that uses multiple signature creation devices the DEP Export is much easier to handle if no certificates are included (since you do not need create new receipt groups).

3.  The sentence "Bei einem Wechsel des Signaturzertifikats muss garantiert sein, dass weitere Belege nicht mehr mit dem vor dem Wechsel verwendeten Zertifikat signiert werden dürfen" (clarified in a discussion with BMF) is only relevant when certificates are not used anymore (e.g. a signature creation device is deactivated), this does not apply to "signing receipts with different signature creation devices".

Summary: 
The DEP Export file does not need to include any certificates.
You can sign receipts with arbitrary signature creation devices in an arbitrary order (of course they need to be valid and registered for the respective company in FinOnline).

If you need an official statement for that:
-V1.1 Detailfragen-RKSV, Chapter 5 (Export des Datenerfassungsprotokolls), there is the paragraph "Gruppierung der Belege, wenn kein Signaturzertifikat vorhanden", also in the subsequent paragraphs there is an example for a DEP without certificates.
-Regarding the use of multiple signature creation devices in an arbitrary order, this is explained in Chapter 1 of V1.1 Detailfragen RKSV, especially in chapter 1.2 - Relations


Does that help?

**Comment by slavok1** [comment]
Thank you for quick answer.
If the certificates are optional in dep-export file, it would be much easy to prepare such file as no separate blocks are inside the file.
