### ISSUE TITLE
Problems with generating proper QR code

### ISSUE THREAD

**Issue by jmatraszek** [a-sit-plus/at-registrierkassen-mustercode#552]
Hi all,
a brief introduction: I am implementing in Ruby an integration with A-Trust to sign transactions and do not speak German, so I have very limited resources I can use. Today I stumbled upon some problem with verifying QR codes in FinanzOnline.

Example QR code looks like this:

`_R1-AT1_A1000117_18_2017-04-05T12:12:23_0,00_0,00_0,00_0,00_0,00_MHF63Jl3phk=_1682746850_2+J1el6iW9E=_oxLv2qJ3R2GmLr7gwcFmX+9ernyfA02pDbKCdO/utV+fqnsHpnmfL+S4Mw2dm5IvPPNp5p121sLfciF0Yd9LiQ==`

It is generated like this:
- the first part is the certificate authority
- the second part is the kassenid of the merchant
- the third part is belegnumber
- the fourth part is the time stamp
- the fifth part is the calculated tax
- the sixth part is the iv
- the parts from seventh to eleventh are the tax per tax group
- the twelfth part is the encrypted turnover counter (or base64 encoded "STO" string in case of the initial transaction)
- the thirteenth part is the certificate serial number
- the fourteenth parts is base64 encoded previous transaction's signature (well, the first 8 chars of it)
- and the last, fifteenth, part is of course the base 64 encoded current transaction's signature.

My questions:
1. part 3: should this be always a number? Should this be a "Startbeleg" string for the initial transaction in each month (or maybe just for the initial transaction globally)?
2. part 13: From registering a merchant in A-Trust I get certificate serial number and certificate hex serial number. Which one should I use? Should it be base64 encoded? I was told that QR code should use the hex serial number, is that right? If yes, then what should be used in a payload of the request to sign a transaction — serial number or hex serial number?
3. part 15: The signature should be at first base64 urlsafe decoded (as it is already urlsafe encoded) then it should be base64 strict encoded. Is that right?
4. Should the QR payload be stripped of `=` chars from base64 encoding? I think no, could you please confirm?
5. Regarding the way the signature is created: I am base64 urlsafe encoding the header and then base64 urlsafe encoding the payload (parts from first to fourteenth joined by `_`). Both are then stripped of trailing `=` and joined using `.`. The result is then base64 urlsafe encoded and also stripped of trailing `=`. This is then send to A-Trust. I was today suggested that this should be hashed using SHA-256 before sending to A-Trust, but I think this is wrong. Could you please confirm?
6. And regarding the way the signature is placed in the QR code: at first it is padded with `=` and base64 urlsafe decoded, then it is base64 strict decoded

I will be extremely grateful if anyone can help me. Thanks in advance!

**Comment by lebail** [comment]
Your description seems somewhat inconsistent since your example has 13 parts (which is correct), but you describe 15 parts. The "calculated tax" and the "iv" should _not_ appear in the code.

"STO" is not used for the initial transaction, but for _cancellations_ (German: "Storno").

Your questions:

1. That's the running number of the receipt. It might be a simple number (1, 2, 3, 4, …), but you can also choose to include other characters (e.g. R-2017-001, R-2017-002, R-2017-003, …) .
2. The serial number should always be used in _hexadecimal_ notation.
3. The signature must be BASE64 "strict" encoded. If your A-Trust command (see 5.) returns it BASE64 urlsafe encoded, then you have to transcode it.
4. In this application, BASE64 "strict" is always used with padding (=), whereas BASE64 urlsafe must not contain any padding. 
5. For signing, A-Trust supports multiple commands you can choose from. You can submit the BASE64 urlsafe encoded header.payload directly, you can BASE64 strict encode this and submit it, or you can create the SHA-256 hash of it and submit it. There is also a command that works with JSON objects.
6. same as 3

**Comment by jmatraszek** [comment]
`STO` - that was of course my error in the issue description. We use it for reversals/refunds. So this is ok.

Is it possible that the QR code fails verification in FinanzOnline because certificate serial number wasn't used in the hexadecimal form (in both places: signing and QR code generation) or was used in hexidecimal form just in QR code generation while the transaction used decimal form? Should it be left padded with `0` to have even number of digits?

**Comment by jmatraszek** [comment]
And regarding the mismatch in the example and the parts I described — I was also wrong the in description (I think it was just too late;)). There are thirteen parts.

**Comment by Phoniexk** [comment]
For registration in FinanzOnline and the content of the QR-Code (maschinenlesbarer Code) always use the hex-code of the serial number. Don't use left padding with zeros for hex-code and also no hex signs like **0h** or **0x**. 

So for the given example in your first post the serial number is **1682746850** -> replace this with hex-code: **644CADE2**

PS: for registration in FinanzOnline it is not explicit required in hex-code, but my experience: it reduces problems for the initial receipt (Startbeleg).

**Comment by jmatraszek** [comment]
Hi @lebail, @Phoniexk,

Thank you so much for your answers! Fixed this by using hex in signing and then in QR code and it was positively verified in FinanzOnline. 🎉
